---
- name: Install dependencies
  ansible.builtin.package:
    name:
      - restic

- name: If not done yet, initialize restic repository
  ansible.builtin.shell: source /opt/backup/restic && (restic snapshots || restic init)

- name: Create script folder
  ansible.builtin.file:
    path: /opt/backup
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Configure backup script
  ansible.builtin.template:
    src: '{{ item.name }}'
    dest: /opt/backup/{{ item.name }}
    mode: '{{ item.mode }}'
    owner: '{{ s3_backup_user }}'
    group: '{{ s3_backup_group }}'
  loop:
    - name: backup
      mode: '0700'
    - name: restic
      mode: '0700'

- name: Install backup service
  ansible.builtin.template:
    src: '{{ item }}'
    dest: /etc/systemd/system/{{ item }}
    mode: '0644'
    owner: root
    group: root
  loop:
    - backup.service
    - backup.timer
  notify: Restart backup

- name: Start backup timer
  ansible.builtin.service:
    name: backup.timer
    state: started
    enabled: true
