---
- name: Install dependencies
  ansible.builtin.package:
    name:
      - restic

- name: Configure backup script and restic.env file
  ansible.builtin.template:
    src: '{{ item.source }}'
    dest: /opt/backup/{{ item.dest }}
    mode: '{{ item.mode }}'
    owner: '{{ s3_backup_user }}'
    group: '{{ s3_backup_group }}'
  loop:
    - source: backup
      dest: backup
      mode: '0700'
    - source: restic.env.j2
      dest: restic.env
      mode: '0700'

- name: If not done yet, initialize restic repository
  ansible.builtin.shell: >
      source /opt/backup/restic.env &&
      (restic snapshots || restic init)
  args:
    executable: /bin/bash

- name: Create script folder
  ansible.builtin.file:
    path: /opt/backup
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Install backup service
  ansible.builtin.template:
    src: '{{ item }}'
    dest: /etc/systemd/system/{{ item }}
    mode: '0644'
    owner: root
    group: root
  loop:
    - backup.service
    - backup.timer
  notify: Restart backup

- name: Start backup timer
  ansible.builtin.service:
    name: backup.timer
    state: started
    enabled: true
