#!/bin/sh

set -o errexit
set -o nounset
set -o xtrace

# Create a temporary directory and switch to that dir
TEMPDIR=$(mktemp -d --suffix=.s3_backup)
cd "${TEMPDIR}"

# Define a cleanup function
clean_up() {
  rm -fr "$TEMPDIR"
  #read the environment variables restic needs
  source /opt/backup/restic
  #delete the snapshots that are older than retention_time days than the creation time of the latest one, regardless of paths
  restic forget --keep-within {{retention_time}}d --group-by host --prune
}

# Set up the trap to call clean_up on exit
trap clean_up EXIT


# Provide easy access to the current date and time
DATE="$(date '+%Y%m%d-%H%M%S')"

{{ s3_backup_script }}

{% if s3_backup_metrics_path %}
echo '# HELP backup_time Time stamp of backup' >"${TEMPDIR}/metrics"
echo '# TYPE backup_time counter' >>"${TEMPDIR}/metrics"
echo 'backup_time{host="{{ inventory_hostname }}"} '"$(date +%s)" >>"${TEMPDIR}/metrics"
{% endif %}
